baseurl = "http://nickazuredevops.github.io"
languageCode = "en-us"
title = "Microsoft Community Hub"
theme = "castanet"
googleAnalytics = ""
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Upcoming Episodes"
    identifier = "upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "User Group"
    identifier = "usergroup"
    url = "/usergroup"
    
[params]
googleAnalytics_UA = ""
mainSections = ["episode"]
episode_number_style  = "brackets"
episode_number_prefix = ""
site_theme = "blue"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
# enable_jumbo = "false"
disable_title_caps = "true"
# truncate = "100"
about_logo = "/img/logo.jpg"
copyright_notice = "Copyright 2023 Nicholas Chang"
youtube_subscribe = ""
itunes_subscribe = ""
spotify_subscribe = "httpss://open.spotify.com/show/..."
# rss_subscribe = "https://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "This is a place for all community learning, including user groups and podcasts. We will be showcasing the Azure Community Enthusiasts User Group and we're excited to announce the upcoming Microsoft Community podcast. Stay tuned!. This website is currently working in progrgress"
  [params.feed]
    copyright = "" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The best podcast ever" #no markdown or HTML
    itunes_author = "" #no markdown or HTML
    itunes_summary = "The HugoCast is the best podcast you've ever seen. You will learn everything you ever needed to know about podcasting from the most inspiring experts to ever show up on the whole internet." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = ""
    itunes_owner_email = "" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "" #fqdn to the image art for your podcast
    language = "en-us"

  [params.realfavicongenerator] # httpss://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
    msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

  # Social links can be given in full URL form or short form
  # In the short form the theme will generate a relevant URL
  [params.social]
    twitter = "https://twitter.com/MS_ComInsights"
    twitter_domain = "" # This domain shows in twitter cards as "View on `twitter_domain`"
    youtube = "https://www.youtube.com/channel/UCs4fPikoCLJhJpA2F97AQuw"
    # Short form in linkedin will link to a user's page so use long form for company pages
    linkedin = "https://www.linkedin.com/company/microsoftcommunityinsights/"
    #linkedin = ""

    [params.authors.Nick]
      name = "Nicholas Chang"
      thumbnail = "img/host/nick.png"
      [params.authors.Nick.social]
        twitter = "nick_cloudops"

