baseurl = "https://example.com/"
languageCode = "en-us"
title = "Microsoft Community Hub"
theme = "castanet"
googleAnalytics = ""
paginate = "9"
buildFuture = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Upcoming Episodes"
    identifier = "upcoming"
    url = "/upcoming"

[[Menu.Main]]
    name = "User Group"
    identifier = "usergroup"
    url = "/usergroup"

[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "/books"

[params]
googleAnalytics_UA = ""
mainSections = ["episode"]
episode_number_style  = "brackets"
episode_number_prefix = "CWC"
site_theme = "blue"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "true"
enable_jumbo = "true"
# enable_jumbo = "false"
disable_title_caps = "true"
# truncate = "100"
# about_logo = "/img/hugocast.png"
youtube_subscribe = ""
spotify_subscribe = "https://open.spotify.com/show/..."
description = "This is a place for all community learning, including user groups and podcasts. We will be showcasing the Azure Community Enthusiasts User Group and we're excited to announce the upcoming Microsoft Community podcast. Stay tuned!"
disqusShortname = ""
